---

development: &default
  adapter: redis
  url: <%= ENV['ACTION_CABLE_BACKEND_URL'] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  url: <%= ENV['REDISTOGO_URL'] %>
